### ISSUE TITLE
ConnectionResetError: [Errno 104] Connection reset by peer

### ISSUE THREAD

**Issue by duanabao** [facebookresearch/habitat-lab#1199]
## Habitat-Lab and Habitat-Sim versions
Habitat-Sim:0.2.1
Habitat: 0.1.7
the branch of habitat-lab is kin2dyn and the branch of habitat-sim is master.

When I run this command 
“python -u -m habitat_baselines.run  --exp-config habitat_baselines/config/pointnav/ddppo_pointnav_quadruped.yaml --run-type train" 
  It reported the following error：

Traceback (most recent call last):
  File "/home/duansh/anaconda3/envs/legged_nav/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/duansh/anaconda3/envs/legged_nav/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/duansh/legged_nav/habitat-lab/habitat_baselines/run.py", line 94, in <module>
    main()
  File "/home/duansh/legged_nav/habitat-lab/habitat_baselines/run.py", line 40, in main
    run_exp(**vars(args))
  File "/home/duansh/legged_nav/habitat-lab/habitat_baselines/run.py", line 90, in run_exp
    execute_exp(config, run_type)
  File "/home/duansh/legged_nav/habitat-lab/habitat_baselines/run.py", line 60, in execute_exp
    trainer.train()
  File "/home/duansh/anaconda3/envs/legged_nav/lib/python3.7/contextlib.py", line 74, in inner
    return func(*args, **kwds)
  File "/home/duansh/legged_nav/habitat-lab/habitat_baselines/rl/ppo/ppo_trainer.py", line 712, in train
    self._init_train()
  File "/home/duansh/legged_nav/habitat-lab/habitat_baselines/rl/ppo/ppo_trainer.py", line 259, in _init_train
    self._init_envs()
  File "/home/duansh/legged_nav/habitat-lab/habitat_baselines/rl/ppo/ppo_trainer.py", line 213, in _init_envs
    workers_ignore_signals=is_slurm_batch_job(),
  File "/home/duansh/legged_nav/habitat-lab/habitat_baselines/utils/env_utils.py", line 105, in construct_envs
    workers_ignore_signals=workers_ignore_signals,
  File "/home/duansh/legged_nav/habitat-lab/habitat/core/vector_env.py", line 194, in __init__
    read_fn() for read_fn in self._connection_read_fns
  File "/home/duansh/legged_nav/habitat-lab/habitat/core/vector_env.py", line 194, in <listcomp>
    read_fn() for read_fn in self._connection_read_fns
  File "/home/duansh/legged_nav/habitat-lab/habitat/core/vector_env.py", line 97, in __call__
    res = self.read_fn()
  File "/home/duansh/legged_nav/habitat-lab/habitat/utils/pickle5_multiprocessing.py", line 68, in recv
    buf = self.recv_bytes()
  File "/home/duansh/anaconda3/envs/legged_nav/lib/python3.7/multiprocessing/connection.py", line 215, in recv_bytes
    buf = self._recv_bytes(maxlength)
  File "/home/duansh/anaconda3/envs/legged_nav/lib/python3.7/multiprocessing/connection.py", line 406, in _recv_bytes
    buf = self._recv(4)
  File "/home/duansh/anaconda3/envs/legged_nav/lib/python3.7/multiprocessing/connection.py", line 378, in _recv
    chunk = read(handle, remaining)
ConnectionResetError: [Errno 104] Connection reset by peer

I tried many methods, but none of them worked. Is there any way? Thank you.

**Comment by dhruvbatra** [comment]
> Habitat-Sim:0.2.1
> Habitat: 0.1.7

We don't support mixing of Hab-Sim and Hab-Lab versions. Please switch to the same version.
