### ISSUE TITLE
X Error of failed request

### ISSUE THREAD

**Issue by taylorlulu** [facebookresearch/habitat-lab#1445]
I'm facing this problem when ran the interactive_play.py. And other examples work properly.
X Error of failed request:  BadAccess (attempt to access private resource denied)
  Major opcode of failed request:  151 (GLX)
  Minor opcode of failed request:  5 (X_GLXMakeCurrent)
  Serial number of failed request:  97
  Current serial number in output stream:  97
I've tried habitat 0.2.4 and habitat 0.2.3 howerver they reported the same error. How can I fix this problem?
I'm using 
![358e049f784d27fa7d58406d19f287d](https://github.com/facebookresearch/habitat-lab/assets/49311079/07b15c9f-6806-45db-ac94-1b2223738fde)
I have no idea this problem was caused by the installtion of habitat or just a driver issue.
I would appreciate your help.

**Comment by NPU-YanChi** [comment]
I also have same question

**Comment by CallmeAG** [comment]
Did you solve it yet? I met the same problem and I don't know what to do with it

**Comment by NPU-YanChi** [comment]
I change the version of habitat-sim and habitat-lab to v0.2.1, then solved. You can try more version.

**Comment by CallmeAG** [comment]
Thanks for the reply. I followed your recommendation changing the habitat-sim and habitat-lab version to v0.2.1. When I install habitat-sim everything goes find.But I got this error when I Did
python setup.py deveplop --all
The exact error output:
Searching for tensorflow==1.13.1
Reading https://pypi.org/simple/tensorflow/
No local packages or working download links found for tensorflow==1.13.1
error: Could not find suitable distribution for Requirement.parse('tensorflow==1.13.1')
Did you have the same problem too?

**Comment by NPU-YanChi** [comment]
maybe you can try other python version, such as 3.6

----- Original Message -----

**Comment by CallmeAG** [comment]
Finally I got no error running the commands trying python version 3.6 to build my conda env
So thankful for your help!

**Comment by 3050671462** [comment]
> Finally I got no error running the commands trying python version 3.6 to build my conda env So thankful for your help!

Could you help me? I also use python = 3.6 and habitat0.2.1(both lab and sim). But after I successfully install all the dependence, I run
python examples/interactive_play.py --never-end
 it failed and output:
UserWarning: WARN: Gym minimally supports python 3.6 as the python foundation not longer supports the version, please update your version to 3.7+
  "Gym minimally supports python 3.6 as the python foundation not longer supports the version, please update your version to 3.7+"
Traceback (most recent call last):
  File "examples/interactive_play.py", line 43, in <module>
    from habitat_baselines.utils.render_wrapper import overlay_frame
  File "/home/qikang/habitat-lab-0.2.1/habitat_baselines/__init__.py", line 7, in <module>
    from habitat_baselines.common.base_il_trainer import BaseILTrainer
  File "/home/qikang/habitat-lab-0.2.1/habitat_baselines/common/base_il_trainer.py", line 10, in <module>
    from habitat_baselines.common.base_trainer import BaseTrainer
  File "/home/qikang/habitat-lab-0.2.1/habitat_baselines/common/base_trainer.py", line 18, in <module>
    from habitat_baselines.common.tensorboard_utils import TensorboardWriter
  File "/home/qikang/habitat-lab-0.2.1/habitat_baselines/common/tensorboard_utils.py", line 11, in <module>
    from torch.utils.tensorboard import SummaryWriter
  File "/home/qikang/miniconda3/envs/habitat/lib/python3.6/site-packages/torch-1.10.2-py3.6-linux-x86_64.egg/torch/utils/tensorboard/__init__.py", line 4, in <module>
    LooseVersion = distutils.version.LooseVersion
AttributeError: module 'distutils' has no attribute 'version'
Have you met the same problem? How can I solve it?

**Comment by EftePA** [comment]
This [suggestion](https://github.com/facebookresearch/habitat-lab/issues/1538#issuecomment-1902985545) solved the error for me, info: ubuntu 22.04, python 3.9. habitat-sim/lab/baselines: 0.3.1. Installed via conda.
