### ISSUE TITLE
Cannot load ReplicaCAD dataset

### ISSUE THREAD

**Issue by man469** [facebookresearch/habitat-lab#1469]
I try to follow the page: https://aihabitat.org/datasets/replica_cad/ to check the ReplicaCAD dataset. I run the command:
python viewer.py --dataset /home/jiefan/data/replica_cad_baked_lighting/replicaCAD_baked.scene_dataset_config.json --scene sc1_staging_00
However I get following error:
Renderer: NVIDIA GeForce RTX 3060/PCIe/SSE2 by NVIDIA Corporation
OpenGL version: 4.6.0 NVIDIA 525.125.06
Using optional features:
    GL_ARB_vertex_array_object
    GL_ARB_separate_shader_objects
    GL_ARB_robustness
    GL_ARB_texture_storage
    GL_ARB_texture_view
    GL_ARB_framebuffer_no_attachments
    GL_ARB_invalidate_subdata
    GL_ARB_texture_storage_multisample
    GL_ARB_multi_bind
    GL_ARB_direct_state_access
    GL_ARB_get_texture_sub_image
    GL_ARB_texture_filter_anisotropic
    GL_KHR_debug
    GL_KHR_parallel_shader_compile
    GL_NV_depth_buffer_float
Using driver workarounds:
    no-forward-compatible-core-context
    no-layout-qualifiers-on-old-glsl
    nv-zero-context-profile-mask
    nv-implementation-color-read-format-dsa-broken
    nv-cubemap-inconsistent-compressed-image-size
    nv-cubemap-broken-full-compressed-image-query
    nv-compressed-block-size-in-bits
[18:45:02:749938]:[Metadata] AttributesManagerBase.h(380)::createFromJsonOrDefaultInternal : <Dataset>: Proposing JSON name : default.scene_dataset_config.json from original name : default| This file does not exist.
[18:45:02:749981]:[Metadata] AssetAttributesManager.cpp(123)::createObject : Asset attributes (capsule3DSolid:capsule3DSolid_hemiRings_4_cylRings_1_segments_12_halfLen_0.75_useTexCoords_false_useTangents_false) created and registered.
[18:45:02:749995]:[Metadata] AssetAttributesManager.cpp(123)::createObject : Asset attributes (capsule3DWireframe:capsule3DWireframe_hemiRings_8_cylRings_1_segments_16_halfLen_1) created and registered.
[18:45:02:750004]:[Metadata] AssetAttributesManager.cpp(123)::createObject : Asset attributes (coneSolid:coneSolid_segments_12_halfLen_1.25_rings_1_useTexCoords_false_useTangents_false_capEnd_true) created and registered.
[18:45:02:750012]:[Metadata] AssetAttributesManager.cpp(123)::createObject : Asset attributes (coneWireframe:coneWireframe_segments_32_halfLen_1.25) created and registered.
[18:45:02:750018]:[Metadata] AssetAttributesManager.cpp(123)::createObject : Asset attributes (cubeSolid:cubeSolid) created and registered.
[18:45:02:750024]:[Metadata] AssetAttributesManager.cpp(123)::createObject : Asset attributes (cubeWireframe:cubeWireframe) created and registered.
[18:45:02:750031]:[Metadata] AssetAttributesManager.cpp(123)::createObject : Asset attributes (cylinderSolid:cylinderSolid_rings_1_segments_12_halfLen_1_useTexCoords_false_useTangents_false_capEnds_true) created and registered.
[18:45:02:750038]:[Metadata] AssetAttributesManager.cpp(123)::createObject : Asset attributes (cylinderWireframe:cylinderWireframe_rings_1_segments_32_halfLen_1) created and registered.
[18:45:02:750044]:[Metadata] AssetAttributesManager.cpp(123)::createObject : Asset attributes (icosphereSolid:icosphereSolid_subdivs_1) created and registered.
[18:45:02:750051]:[Metadata] AssetAttributesManager.cpp(123)::createObject : Asset attributes (icosphereWireframe:icosphereWireframe_subdivs_1) created and registered.
[18:45:02:750058]:[Metadata] AssetAttributesManager.cpp(123)::createObject : Asset attributes (uvSphereSolid:uvSphereSolid_rings_8_segments_16_useTexCoords_false_useTangents_false) created and registered.
[18:45:02:750064]:[Metadata] AssetAttributesManager.cpp(123)::createObject : Asset attributes (uvSphereWireframe:uvSphereWireframe_rings_16_segments_32) created and registered.
[18:45:02:750069]:[Metadata] AssetAttributesManager.cpp(112)::AssetAttributesManager : Built default primitive asset templates : 12
[18:45:02:750157]:[Metadata] SceneDatasetAttributesManager.cpp(37)::createObject : File (default) not found, so new default dataset attributes created  and registered.
[18:45:02:750161]:[Metadata] MetadataMediator.cpp(120)::createSceneDataset : Dataset default successfully created.
[18:45:02:750169]:[Metadata] AttributesManagerBase.h(380)::createFromJsonOrDefaultInternal : <Physics Manager>: Proposing JSON name : ./data/default.physics_config.json from original name : ./data/default.physics_config.json| This file does not exist.
[18:45:02:750176]:[Metadata] PhysicsAttributesManager.cpp(26)::createObject : File (./data/default.physics_config.json) not found, so new default physics manager attributes created and registered.
[18:45:02:750180]:[Metadata] MetadataMediator.cpp(210)::setActiveSceneDatasetName : Attempting to create new dataset /home/jiefan/data/replica_cad_baked_lighting/replicaCAD_baked.scene_dataset_config.json
[18:45:02:750184]:[Metadata] AttributesManagerBase.h(380)::createFromJsonOrDefaultInternal : <Dataset>: Proposing JSON name : /home/jiefan/data/replica_cad_baked_lighting/replicaCAD_baked.scene_dataset_config.json from original name : /home/jiefan/data/replica_cad_baked_lighting/replicaCAD_baked.scene_dataset_config.json| This file does not exist.
[18:45:02:750194]:[Metadata] AssetAttributesManager.cpp(123)::createObject : Asset attributes (capsule3DSolid:capsule3DSolid_hemiRings_4_cylRings_1_segments_12_halfLen_0.75_useTexCoords_false_useTangents_false) created and registered.
[18:45:02:750202]:[Metadata] AssetAttributesManager.cpp(123)::createObject : Asset attributes (capsule3DWireframe:capsule3DWireframe_hemiRings_8_cylRings_1_segments_16_halfLen_1) created and registered.
[18:45:02:750210]:[Metadata] AssetAttributesManager.cpp(123)::createObject : Asset attributes (coneSolid:coneSolid_segments_12_halfLen_1.25_rings_1_useTexCoords_false_useTangents_false_capEnd_true) created and registered.
[18:45:02:750216]:[Metadata] AssetAttributesManager.cpp(123)::createObject : Asset attributes (coneWireframe:coneWireframe_segments_32_halfLen_1.25) created and registered.
[18:45:02:750222]:[Metadata] AssetAttributesManager.cpp(123)::createObject : Asset attributes (cubeSolid:cubeSolid) created and registered.
[18:45:02:750227]:[Metadata] AssetAttributesManager.cpp(123)::createObject : Asset attributes (cubeWireframe:cubeWireframe) created and registered.
[18:45:02:750233]:[Metadata] AssetAttributesManager.cpp(123)::createObject : Asset attributes (cylinderSolid:cylinderSolid_rings_1_segments_12_halfLen_1_useTexCoords_false_useTangents_false_capEnds_true) created and registered.
[18:45:02:750240]:[Metadata] AssetAttributesManager.cpp(123)::createObject : Asset attributes (cylinderWireframe:cylinderWireframe_rings_1_segments_32_halfLen_1) created and registered.
[18:45:02:750246]:[Metadata] AssetAttributesManager.cpp(123)::createObject : Asset attributes (icosphereSolid:icosphereSolid_subdivs_1) created and registered.
[18:45:02:750252]:[Metadata] AssetAttributesManager.cpp(123)::createObject : Asset attributes (icosphereWireframe:icosphereWireframe_subdivs_1) created and registered.
[18:45:02:750258]:[Metadata] AssetAttributesManager.cpp(123)::createObject : Asset attributes (uvSphereSolid:uvSphereSolid_rings_8_segments_16_useTexCoords_false_useTangents_false) created and registered.
[18:45:02:750264]:[Metadata] AssetAttributesManager.cpp(123)::createObject : Asset attributes (uvSphereWireframe:uvSphereWireframe_rings_16_segments_32) created and registered.
[18:45:02:750268]:[Metadata] AssetAttributesManager.cpp(112)::AssetAttributesManager : Built default primitive asset templates : 12
[18:45:02:750339]:[Metadata] SceneDatasetAttributesManager.cpp(37)::createObject : File (/home/jiefan/data/replica_cad_baked_lighting/replicaCAD_baked.scene_dataset_config.json) not found, so new default dataset attributes created  and registered.
[18:45:02:750342]:[Metadata] MetadataMediator.cpp(120)::createSceneDataset : Dataset /home/jiefan/data/replica_cad_baked_lighting/replicaCAD_baked.scene_dataset_config.json successfully created.
[18:45:02:750346]:[Metadata] MetadataMediator.cpp(217)::setActiveSceneDatasetName : Attempt to create new dataset /home/jiefan/data/replica_cad_baked_lighting/replicaCAD_baked.scene_dataset_config.json   succeeded. Currently active dataset : /home/jiefan/data/replica_cad_baked_lighting/replicaCAD_baked.scene_dataset_config.json
[18:45:02:750350]:[Metadata] AttributesManagerBase.h(380)::createFromJsonOrDefaultInternal : <Physics Manager>: Proposing JSON name : data/default.physics_config.json from original name : data/default.physics_config.json| This file does not exist.
[18:45:02:750355]:[Metadata] PhysicsAttributesManager.cpp(26)::createObject : File (data/default.physics_config.json) not found, so new default physics manager attributes created and registered.
[18:45:02:750359]:[Metadata] MetadataMediator.cpp(66)::setSimulatorConfiguration : Set new simulator config for scene/stage : sc1_staging_00 and dataset : /home/jiefan/data/replica_cad_baked_lighting/replicaCAD_baked.scene_dataset_config.json which is currently active dataset.
PluginManager::Manager: duplicate static plugin AnyImageImporter, ignoring
PluginManager::Manager: duplicate static plugin AssimpImporter, ignoring
PluginManager::Manager: duplicate static plugin AnySceneImporter, ignoring
[18:45:02:764578]:[Metadata] MetadataMediator.cpp(297)::getSceneInstanceAttributesByName : Dataset : /home/jiefan/data/replica_cad_baked_lighting/replicaCAD_baked.scene_dataset_config.json has no preloaded SceneInstanceAttributes or StageAttributes named : sc1_staging_00 so loading/creating a new StageAttributes with this name, and then creating a SceneInstanceAttributes with the same name that references this stage.
[18:45:02:764587]:[Metadata] AttributesManagerBase.h(380)::createFromJsonOrDefaultInternal : <Stage Template>: Proposing JSON name : sc1_staging_00.stage_config.json from original name : sc1_staging_00| This file does not exist.
[18:45:02:764606]:[Metadata] StageAttributesManager.cpp(86)::registerObjectFinalize : Render asset template handle : sc1_staging_00 specified in stage template with handle : sc1_staging_00 does not correspond to any existing file or primitive render asset.  Aborting.
[18:45:02:764671]:[Scene] SceneManager.h(21)::~SceneManager : Deconstructing SceneManager
[18:45:02:764718]:[Gfx] Renderer.cpp(71)::~Impl : Deconstructing Renderer
Traceback (most recent call last):
  File "/home/jiefan/habitat-sim/examples/viewer.py", line 1159, in <module>
    HabitatSimInteractiveViewer(sim_settings).exec()
  File "/home/jiefan/habitat-sim/examples/viewer.py", line 181, in __init__
    self.reconfigure_sim()
  File "/home/jiefan/habitat-sim/examples/viewer.py", line 364, in reconfigure_sim
    self.tiled_sims.append(habitat_sim.Simulator(self.cfg))
  File "<attrs generated init habitat_sim.simulator.Simulator>", line 11, in __init__
  File "/home/jiefan/anaconda3/envs/habitat/lib/python3.9/site-packages/habitat_sim-0.2.4-py3.9-linux-x86_64.egg/habitat_sim/simulator.py", line 119, in __attrs_post_init__
    self.__set_from_config(self.config)
  File "/home/jiefan/anaconda3/envs/habitat/lib/python3.9/site-packages/habitat_sim-0.2.4-py3.9-linux-x86_64.egg/habitat_sim/simulator.py", line 270, in __set_from_config
    self._config_backend(config)
  File "/home/jiefan/anaconda3/envs/habitat/lib/python3.9/site-packages/habitat_sim-0.2.4-py3.9-linux-x86_64.egg/habitat_sim/simulator.py", line 201, in _config_backend
    super().__init__(config.sim_cfg, config.metadata_mediator)
AssertionError: ESP_CHECK failed: Missing (at least) one of scene dataset attributes, stage attributes, or dataset scene attributes for scene 'sc1_staging_00'.  Likely an invalid scene name.

Could somebody help? Thank you very much!

**Comment by aclegg3** [comment]
> (/home/jiefan/data/replica_cad_baked_lighting/replicaCAD_baked.scene_dataset_config.json) not found, so new default dataset attributes created and registered.

Hey @man469 looks like your dataset is not located at the global path you have provided to the viewer.
