### ISSUE TITLE
M1 Mac hangs when running habitat_baselines on ppo_pointnav_example.yaml

### ISSUE THREAD

**Issue by afterless** [facebookresearch/habitat-lab#1501]
## Habitat-Lab and Habitat-Sim versions
Habitat-Lab: v0.2.5
Habitat-Sim: v0.2.5

**How did you install the code?**
Installed by following the official tutorial on the README using a Rosetta2 emulated terminal, with the following exceptions:
- I setup the environment flag `CONDA_SUBDIR=osx-64` so I could properly install dependencies that didn't have an arm64 equivalent.
- After finishing the installation instructions, I ran `pip uninstall numpy scipy` and then `pip install numpy==1.23.0 scipy` as I would otherwise have the following error when running `habitat_baselines.run`: 
  -  ```omp: error #15: initializing libiomp5.dylib, but found libomp.dylib already initialized.```

**Are you using a conda env?**
I am using an environment I instantiated in a folder that also contains the habitat lab repository, such that the file structure is as follows:
```
dhruv_proj
├── .env # conda environment
└── habitat-lab
```

**What python version are you using?**
The version of python and cmake that the official tutorial had specified, `python=3.9` and `cmake=3.14.0`

**What data do you use?**
I downloaded the datasets `habitat_test_scenes` and `habitat_test_pointnav_dataset` by following the first step in the Testing section of the README

## ❓ Questions and Help
To ensure that all my packages installed correctly and for the first step in a project, I ran the following train code in `habitat_baselines`.
```
python -u -m habitat_baselines.run \
  --config-name=pointnav/ppo_pointnav_example.yaml
```
but however I run into the following error: 
```
[09:51:26:033186]:[Warning]:[Assets] ResourceManager.cpp(353)::loadSemanticSceneDescriptor : SSD File Naming Issue! Neither SceneInstanceAttributes-provided name : `data/scene_datasets/habitat-test-scenes/skokloster-castle.scn` nor constructed filename : `data/scene_datasets/habitat-test-scenes/info_semantic.json` exist on disk.
Error executing job with overrides: []
Traceback (most recent call last):
  File "/Users/afterless/projects/dhruv_proj/.env/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Users/afterless/projects/dhruv_proj/.env/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/afterless/projects/dhruv_proj/habitat-lab/habitat-baselines/habitat_baselines/run.py", line 77, in <module>
    main()
  File "/Users/afterless/projects/dhruv_proj/.env/lib/python3.9/site-packages/hydra/main.py", line 94, in decorated_main
    _run_hydra(
  File "/Users/afterless/projects/dhruv_proj/.env/lib/python3.9/site-packages/hydra/_internal/utils.py", line 394, in _run_hydra
    _run_app(
  File "/Users/afterless/projects/dhruv_proj/.env/lib/python3.9/site-packages/hydra/_internal/utils.py", line 457, in _run_app
    run_and_report(
  File "/Users/afterless/projects/dhruv_proj/.env/lib/python3.9/site-packages/hydra/_internal/utils.py", line 223, in run_and_report
    raise ex
  File "/Users/afterless/projects/dhruv_proj/.env/lib/python3.9/site-packages/hydra/_internal/utils.py", line 220, in run_and_report
    return func()
  File "/Users/afterless/projects/dhruv_proj/.env/lib/python3.9/site-packages/hydra/_internal/utils.py", line 458, in <lambda>
    lambda: hydra.run(
  File "/Users/afterless/projects/dhruv_proj/.env/lib/python3.9/site-packages/hydra/_internal/hydra.py", line 132, in run
    _ = ret.return_value
  File "/Users/afterless/projects/dhruv_proj/.env/lib/python3.9/site-packages/hydra/core/utils.py", line 260, in return_value
    raise self._return_value
  File "/Users/afterless/projects/dhruv_proj/.env/lib/python3.9/site-packages/hydra/core/utils.py", line 186, in run_job
    ret.return_value = task_function(task_cfg)
  File "/Users/afterless/projects/dhruv_proj/habitat-lab/habitat-baselines/habitat_baselines/run.py", line 31, in main
    execute_exp(cfg, "eval" if cfg.habitat_baselines.evaluate else "train")
  File "/Users/afterless/projects/dhruv_proj/habitat-lab/habitat-baselines/habitat_baselines/run.py", line 60, in execute_exp
    trainer.train()
  File "/Users/afterless/projects/dhruv_proj/.env/lib/python3.9/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/Users/afterless/projects/dhruv_proj/habitat-lab/habitat-baselines/habitat_baselines/rl/ppo/ppo_trainer.py", line 657, in train
    self._init_train(resume_state)
  File "/Users/afterless/projects/dhruv_proj/habitat-lab/habitat-baselines/habitat_baselines/rl/ppo/ppo_trainer.py", line 248, in _init_train
    self._init_envs()
  File "/Users/afterless/projects/dhruv_proj/habitat-lab/habitat-baselines/habitat_baselines/rl/ppo/ppo_trainer.py", line 146, in _init_envs
    self.envs = env_factory.construct_envs(
  File "/Users/afterless/projects/dhruv_proj/habitat-lab/habitat-baselines/habitat_baselines/common/habitat_env_factory.py", line 111, in construct_envs
    envs = vector_env_cls(
  File "/Users/afterless/projects/dhruv_proj/habitat-lab/habitat-lab/habitat/core/vector_env.py", line 207, in __init__
    self.observation_spaces = [
  File "/Users/afterless/projects/dhruv_proj/habitat-lab/habitat-lab/habitat/core/vector_env.py", line 208, in <listcomp>
    read_fn() for read_fn in self._connection_read_fns
  File "/Users/afterless/projects/dhruv_proj/habitat-lab/habitat-lab/habitat/core/vector_env.py", line 110, in __call__
    res = self.read_fn()
  File "/Users/afterless/projects/dhruv_proj/habitat-lab/habitat-lab/habitat/utils/pickle5_multiprocessing.py", line 68, in recv
    buf = self.recv_bytes()
  File "/Users/afterless/projects/dhruv_proj/.env/lib/python3.9/multiprocessing/connection.py", line 216, in recv_bytes
    buf = self._recv_bytes(maxlength)
  File "/Users/afterless/projects/dhruv_proj/.env/lib/python3.9/multiprocessing/connection.py", line 414, in _recv_bytes
    buf = self._recv(4)
  File "/Users/afterless/projects/dhruv_proj/.env/lib/python3.9/multiprocessing/connection.py", line 383, in _recv
    raise EOFError
EOFError
Exception ignored in: <function VectorEnv.__del__ at 0x16d101940>
Traceback (most recent call last):
  File "/Users/afterless/projects/dhruv_proj/habitat-lab/habitat-lab/habitat/core/vector_env.py", line 615, in __del__
  File "/Users/afterless/projects/dhruv_proj/habitat-lab/habitat-lab/habitat/core/vector_env.py", line 467, in close
  File "/Users/afterless/projects/dhruv_proj/habitat-lab/habitat-lab/habitat/core/vector_env.py", line 110, in __call__
  File "/Users/afterless/projects/dhruv_proj/habitat-lab/habitat-lab/habitat/utils/pickle5_multiprocessing.py", line 68, in recv
  File "/Users/afterless/projects/dhruv_proj/.env/lib/python3.9/multiprocessing/connection.py", line 216, in recv_bytes
  File "/Users/afterless/projects/dhruv_proj/.env/lib/python3.9/multiprocessing/connection.py", line 414, in _recv_bytes
  File "/Users/afterless/projects/dhruv_proj/.env/lib/python3.9/multiprocessing/connection.py", line 383, in _recv
EOFError:
```
If I instead rerun the above command with the `habitat_baselines.trainer_name=ver` flag, then it prints the following output and just hangs:
```
PluginManager::Manager: duplicate static plugin StbImageImporter, ignoring
PluginManager::Manager: duplicate static plugin AnyImageImporter, ignoring
PluginManager::Manager: duplicate static plugin StbImageImporter, ignoring
PluginManager::Manager: duplicate static plugin AnyImageImporter, ignoring
PluginManager::Manager: duplicate static plugin GltfImporterPluginManager::Manager: duplicate static plugin, ignoring
GltfImporter, ignoring
2023-08-15 13:29:07,590 Initializing dataset PointNav-v1
2023-08-15 13:29:07,830 initializing sim Sim-v0
PluginManager::Manager: duplicate static plugin AssimpImporter, ignoring
PluginManager::Manager: duplicate static plugin BasisImporter, ignoring
PluginManager::Manager: duplicate static plugin AnySceneImporter, ignoring
PluginManager::Manager: duplicate static plugin StbImageImporter, ignoring
PluginManager::Manager: duplicate static plugin AnyImageImporter, ignoring
PluginManager::Manager: duplicate static plugin GltfImporter, ignoring
Renderer: Apple M1 by Apple
OpenGL version: 4.1 Metal - 76.3
Using optional features:
    GL_ARB_vertex_array_object
    GL_ARB_ES2_compatibility
    GL_ARB_separate_shader_objects
    GL_ARB_texture_storage
    GL_EXT_texture_filter_anisotropic
    GL_EXT_debug_label
    GL_EXT_debug_marker
Using driver workarounds:
    no-layout-qualifiers-on-old-glsl
    apple-buffer-texture-unbind-on-buffer-modify
[09:53:28:535808]:[Warning]:[Assets] ResourceManager.cpp(353)::loadSemanticSceneDescriptor : SSD File Naming Issue! Neither SceneInstanceAttributes-provided name : `data/scene_datasets/habitat-test-scenes/skokloster-castle.scn` nor constructed filename : `data/scene_datasets/habitat-test-scenes/info_semantic.json` exist on disk.
PluginManager::Manager: duplicate static plugin AssimpImporter, ignoring
PluginManager::Manager: duplicate static plugin BasisImporter, ignoring
PluginManager::Manager: duplicate static plugin AnySceneImporter, ignoring
PluginManager::Manager: duplicate static plugin StbImageImporter, ignoring
PluginManager::Manager: duplicate static plugin AnyImageImporter, ignoring
PluginManager::Manager: duplicate static plugin GltfImporter, ignoring
```
It seems that the issue is related to OpenMP and multiprocessing given the previous issues I had mentioned above, but I'm not sure if the warning regarding the SSD File Naming issue might have anything to do with it. Any tips are appreciated as well and feedback on if I should submit this issue anywhere else. Thank you for the help!

**Comment by afterless** [comment]
Seemingly running `export HABITAT_ENV_DEBUG=1` and then `unset HABITAT_ENV_DEBUG` fixed the issue and now it runs fine. Not sure as to why this is, but now it runs smoothly. Will close this issue
