### ISSUE TITLE
Problem running hitl minimal example, has no attribute 'creation_attribute'

### ISSUE THREAD

**Issue by Coelancanth** [facebookresearch/habitat-lab#1763]
## Habitat-Lab and Habitat-Sim versions
Habitat-Lab: master?

Habitat-Sim: master?

Habitat is under active development, and we advise users to restrict themselves to stable releases. Are you using the latest release versions of [Habitat-Lab](https://github.com/facebookresearch/habitat-lab/releases) and [Habitat-Sim](https://github.com/facebookresearch/habitat-sim/releases)? Your question may already be addressed in the latest versions. We may also not be able to help with problems in earlier versions because they sometimes lack the more verbose logging needed for debugging.

Master branch contains 'bleeding edge' code and should be used at your own risk.

## Docs and Tutorials
Did you read the docs? https://aihabitat.org/docs/habitat-lab/

Did you check out the tutorials? https://aihabitat.org/tutorial/2020/

Perhaps your question is answered there. If not, carry on!

## ❓ Questions and Help
[06:12:49:740270]:[Warning]:[Assets] ResourceManager.cpp(945)::createRenderAssetInstance : Instantiating render asset `data/humanoids/humanoid_data/female_2/female_2.glb` with incompatible light setup, instance will not be correctly lit. For objects, please ensure 'requires lighting' is enabled in object config file.
Error executing job with overrides: []
Traceback (most recent call last):
  File "/home/coel/thesis/habitat-lab/examples/hitl/minimal/minimal.py", line 54, in main
    hitl_main(config, lambda app_service: AppStateMinimal(app_service))
  File "/home/coel/thesis/habitat-lab/habitat-hitl/habitat_hitl/core/hitl_main.py", line 83, in hitl_main
    driver = HitlDriver(
  File "/home/coel/thesis/habitat-lab/habitat-hitl/habitat_hitl/_internal/hitl_driver.py", line 59, in wrapper
    return callable_(*args, **kwds)
  File "/home/coel/thesis/habitat-lab/habitat-hitl/habitat_hitl/_internal/hitl_driver.py", line 185, in __init__
    self._reset_environment()
  File "/home/coel/thesis/habitat-lab/habitat-hitl/habitat_hitl/_internal/hitl_driver.py", line 304, in _reset_environment
    self._obs, self._metrics = self.gym_habitat_env.reset(return_info=True)
  File "/home/coel/miniconda3/envs/habitat_hitl/lib/python3.9/site-packages/gym/core.py", line 283, in reset
    return self.env.reset(**kwargs)
  File "/home/coel/thesis/habitat-lab/habitat-lab/habitat/gym/gym_wrapper.py", line 319, in reset
    obs = self.env.reset(*args, return_info=return_info, **kwargs)
  File "/home/coel/thesis/habitat-lab/habitat-lab/habitat/core/environments.py", line 62, in reset
    return super().reset(*args, return_info=return_info, **kwargs)
  File "/home/coel/miniconda3/envs/habitat_hitl/lib/python3.9/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/home/coel/thesis/habitat-lab/habitat-lab/habitat/core/env.py", line 425, in reset
    observations = self._env.reset()
  File "/home/coel/thesis/habitat-lab/habitat-lab/habitat/core/env.py", line 261, in reset
    self.reconfigure(self._config)
  File "/home/coel/thesis/habitat-lab/habitat-lab/habitat/core/env.py", line 343, in reconfigure
    self._sim.reconfigure(self._config.simulator, self.current_episode)
  File "/home/coel/thesis/habitat-lab/habitat-lab/habitat/tasks/rearrange/utils.py", line 718, in wrapper
    ret = f(self, *args, **kwargs)
  File "/home/coel/thesis/habitat-lab/habitat-lab/habitat/tasks/rearrange/rearrange_sim.py", line 333, in reconfigure
    self._add_objs(ep_info, should_add_objects, new_scene)
  File "/home/coel/thesis/habitat-lab/habitat-lab/habitat/tasks/rearrange/utils.py", line 718, in wrapper
    ret = f(self, *args, **kwargs)
  File "/home/coel/thesis/habitat-lab/habitat-lab/habitat/tasks/rearrange/rearrange_sim.py", line 639, in _add_objs
    self._receptacles = self._create_recep_info(
  File "/home/coel/thesis/habitat-lab/habitat-lab/habitat/tasks/rearrange/rearrange_sim.py", line 659, in _create_recep_info
    all_receps = find_receptacles(
  File "/home/coel/thesis/habitat-lab/habitat-lab/habitat/datasets/rearrange/samplers/receptacle.py", line 757, in find_receptacles
    creation_attr = obj.creation_attributes
AttributeError: 'habitat_sim._ext.habitat_sim_bindings.ManagedBulle' object has no attribute 'creation_attributes'

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
corrupted size vs. prev_size
Aborted (core dumped)

Is it caused by the OS? I am using Ubuntu 22.04

**Comment by Coelancanth** [comment]
the reason of this error is that I didn't install the nightly sim version.
