### ISSUE TITLE
Unable to evaluate the Social Navigate Benchmark in Habitat 3.0 using the social_nav_latest.pth checkpoint. AttributeError: Can't get attribute 'HeadStereoLeftDepthSensorConfig' 

### ISSUE THREAD

**Issue by vaibhavoutat** [facebookresearch/habitat-lab#1839]
## Habitat-Lab and Habitat-Sim versions
Stable branch
Habitat-Lab: v3.0.0
Habitat-Sim: v3.0.0

Habitat is under active development, and we advise users to restrict themselves to stable releases of [Habitat-Lab](https://github.com/facebookresearch/habitat-lab/releases) and [Habitat-Sim](https://github.com/facebookresearch/habitat-sim/releases). The bug you are about to report may already be fixed in the latest version.

Master branch contains 'bleeding edge' code, but we do appreciate bug reports for it!

## 🐛 Bug

AttributeError: Can't get attribute 'HeadStereoLeftDepthSensorConfig' on <module 'habitat.config.default_structured_configs'

## Steps to Reproduce
I just ran the evalution code mentioned in the Habitat baseline readme. Command mentioned below.

python habitat-baselines/habitat_baselines/run.py --config-name=social_nav/social_nav.yaml habitat_baselines.evaluate=True habitat_baselines.eval_ckpt_path_dir=/home/deepbot/habitat/habitatweek/habitat-lab/data/datasets/hssd/rearrange/checkpoint/social_nav_latest.pth habitat_baselines.eval.should_load_ckpt=True

Please note that without a minimal working example to reproduce the bug, we may not be able to help you.

I got the following error.

python habitat-baselines/habitat_baselines/run.py --config-name=social_nav/social_nav.yaml habitat_baselines.evaluate=True habitat_baselines.eval_ckpt_path_dir=/home/deepbot/habitat/habitatweek/habitat-lab/data/datasets/hssd/rearrange/checkpoint/social_nav_latest.pth habitat_baselines.eval.should_load_ckpt=True
Error executing job with overrides: ['habitat_baselines.evaluate=True', 'habitat_baselines.eval_ckpt_path_dir=/home/deepbot/habitat/habitatweek/habitat-lab/data/datasets/hssd/rearrange/checkpoint/social_nav_latest.pth', 'habitat_baselines.eval.should_load_ckpt=True']
Traceback (most recent call last):
  File "/home/deepbot/habitat/habitatweek/habitat-lab/habitat-baselines/habitat_baselines/run.py", line 31, in main
    execute_exp(cfg, "eval" if cfg.habitat_baselines.evaluate else "train")
  File "/home/deepbot/habitat/habitatweek/habitat-lab/habitat-baselines/habitat_baselines/run.py", line 62, in execute_exp
    trainer.eval()
  File "/home/deepbot/habitat/habitatweek/habitat-lab/habitat-baselines/habitat_baselines/common/base_trainer.py", line 129, in eval
    self._eval_checkpoint(
  File "/home/deepbot/habitat/habitatweek/habitat-lab/habitat-baselines/habitat_baselines/rl/ppo/ppo_trainer.py", line 826, in _eval_checkpoint
    ckpt_dict = self.load_checkpoint(
  File "/home/deepbot/habitat/habitatweek/habitat-lab/habitat-baselines/habitat_baselines/rl/ppo/ppo_trainer.py", line 341, in load_checkpoint
    return torch.load(checkpoint_path, *args, **kwargs)
  File "/home/deepbot/miniforge3/envs/habitatweek/lib/python3.9/site-packages/torch/serialization.py", line 1026, in load
    return _load(opened_zipfile,
  File "/home/deepbot/miniforge3/envs/habitatweek/lib/python3.9/site-packages/torch/serialization.py", line 1438, in _load
    result = unpickler.load()
  File "/home/deepbot/miniforge3/envs/habitatweek/lib/python3.9/site-packages/torch/serialization.py", line 1431, in find_class
    return super().find_class(mod_name, name)
AttributeError: Can't get attribute 'HeadStereoLeftDepthSensorConfig' on <module 'habitat.config.default_structured_configs' from '/home/deepbot/habitat/habitatweek/habitat-lab/habitat-lab/habitat/config/default_structured_configs.py'>

## Expected behavior

Evaluation of the agent on the test scenes with a video of how the agent is performing.

Kindly let me know how to proceed.

**Comment by mengmeng6660** [comment]
Delete the file `data/new_checkpoints/..habitat-resume-state.pth`.
