### ISSUE TITLE
Basic Example of construct_envs

### ISSUE THREAD

**Issue by frasermcghan** [facebookresearch/habitat-lab#592]
## ❓ Questions and Help

Hi,

Would anyone be able to provide a simple working example of how to use the construct_envs function?

I've tried the following code so far but I'm getting an error about TASK_CONFIG - what is the recommended usage?

```python
from habitat.core.env import Env
from habitat_baselines.utils.env_utils import construct_envs
from habitat.config.default import get_config

if __name__ == "__main__":

    basic_config = get_config()
    basic_config.defrost()
    basic_config.NUM_PROCESSES = 4
    basic_config.freeze()

    envs = construct_envs(config=basic_config, env_class=Env)
```

```
Traceback (most recent call last):
  File "/home/fraser/habitat_baseline_testing/dqn_agent.py", line 12, in <module>
    envs = construct_envs(config=basic_config, env_class=Env)
  File "/home/fraser/habitat_baseline_testing/habitat_installation/HabitatChallenge/habitat-lab/habitat_baselines/utils/env_utils.py", line 56, in construct_envs
    dataset = make_dataset(config.TASK_CONFIG.DATASET.TYPE)
  File "/home/fraser/miniconda3/envs/habitat/lib/python3.6/site-packages/yacs/config.py", line 141, in __getattr__
    raise AttributeError(name)
AttributeError: TASK_CONFIG
```

Any help would be greatly appreciated :)

Thanks

**Comment by frasermcghan** [comment]
Think I worked it out...Just had to merge parts of the baseline config into the default config.

This is how I got each scene in the validation set to run in parallel on 14 separate processes:

```python
import habitat
from habitat_baselines.utils.env_utils import (
    make_env_fn,
    construct_envs,
)
from habitat_baselines.config.default import get_config


def vector_example():
    """
    Initialises a `habitat.VectorEnv` environment, then takes random steps.
    """

    baseline_config = get_config("configs/tasks/pointnav.yaml")
    config = habitat.get_config("configs/tasks/pointnav.yaml")

    config.defrost()
    config.TASK_CONFIG = baseline_config.TASK_CONFIG
    config.NUM_ENVIRONMENTS = 14
    config.SENSORS = baseline_config.SENSORS
    config.SIMULATOR_GPU_ID = 0
    config.freeze()

    env_class = habitat.Env
    envs = construct_envs(config, env_class)

    _ = envs.reset()

    n_steps = 500
    n_envs = envs.num_envs
    n_episodes = envs.number_of_episodes[0]

    for episode in range(n_episodes):
        count_steps = 0
        print(
            f"Starting episode {episode}/{n_episodes} in parallel processes across {n_envs} environments."
        )
        scene_names = [
            ep.scene_id.split("/")[-1].strip(".glb") for ep in envs.current_episodes()
        ]

        for i, scene in enumerate(scene_names):
            print(f"Stepping around in Environment {i+1}: {scene}..")

        for step in range(n_steps):
            random_actions = [
                action_space.sample() for action_space in envs.action_spaces
            ]
            _ = envs.step(random_actions)
            count_steps += 1

        print("Episodes finished after {} steps.".format(count_steps))


if __name__ == "__main__":
    example()
```
