### ISSUE TITLE
ValueError: Argument 'goals' must be set

### ISSUE THREAD

**Issue by AshwiniUthir** [facebookresearch/habitat-lab#702]
Hi, I am new to Habitat. I am trying to run the example given in "https://aihabitat.org/docs/habitat-lab/quickstart.html" and I am running into the below error:
```
2021-08-04 12:59:40,895 Initializing dataset PointNav-v1
Traceback (most recent call last):
  File "example_pointnav_AU.py", line 70, in <module>
    example()
  File "example_pointnav_AU.py", line 18, in example
    config=habitat.get_config("/configs/tasks/pointnav.yaml")
  File "/habitat-sim/habitat-lab/habitat/core/env.py", line 79, in __init__
    id_dataset=config.DATASET.TYPE, config=config.DATASET
  File "/habitat-sim/habitat-lab/habitat/datasets/registration.py", line 21, in make_dataset
    return _dataset(**kwargs)  # type: ignore
  File "/habitat-sim/habitat-lab/habitat/datasets/pointnav/pointnav_dataset.py", line 95, in __init__
    self.from_json(f.read(), scenes_dir=config.SCENES_DIR)
  File "/habitat-sim/habitat-lab/habitat/datasets/pointnav/pointnav_dataset.py", line 132, in from_json
    episode = NavigationEpisode(**episode)
  File "<attrs generated init habitat.tasks.nav.nav.NavigationEpisode>", line 16, in __init__
  File "/habitat-sim/habitat-lab/habitat/core/utils.py", line 66, in not_none_validator
    raise ValueError(f"Argument '{attribute.name}' must be set")
ValueError: Argument 'goals' must be set
```

Can someone help me resolve this?

**Comment by AshwiniUthir** [comment]
Fresh installation of Habitat solved this issue.
