### ISSUE TITLE
Trainer crashed when training a fresh PPO agent on mp3d validation set

### ISSUE THREAD

**Issue by yhymason** [facebookresearch/habitat-lab#766]
Hi there,

As a part of the debugging efforts towards the issues I encountered in [this post](https://github.com/facebookresearch/habitat-lab/issues/765). I have tried to set up a trainer using the mp3d validation dataset with the following configs:
ppo_pointnav.yaml:
```
BASE_TASK_CONFIG_PATH: "/home/lci-user/Desktop/workspace/src/ros_x_habitat/configs/training_configs/pointnav_rgbd_mp3d_validation_scenes.yaml"
TRAINER_NAME: "ppo"
ENV_NAME: "NavRLEnv"
SIMULATOR_GPU_ID: 0
TORCH_GPU_ID: 0
# Can be uncommented to generate videos.
VIDEO_OPTION: [ "disk", "tensorboard" ]
TENSORBOARD_DIR: "tb"
VIDEO_DIR: "video_dir"
# Evaluate on all episodes
TEST_EPISODE_COUNT: -1
EVAL_CKPT_PATH_DIR: "data/new_checkpoints"
SENSORS: [ "DEPTH_SENSOR" ]
CHECKPOINT_FOLDER: "data/new_checkpoints"
NUM_UPDATES: -1
TOTAL_NUM_STEPS: 1e10
LOG_INTERVAL: 25
NUM_CHECKPOINTS: 100
# Force PyTorch to be single threaded as
# this improves performance considerably
FORCE_TORCH_SINGLE_THREADED: True

RL:
  PPO:
    # ppo params
    clip_param: 0.2
    ppo_epoch: 4
    value_loss_coef: 0.5
    entropy_coef: 0.01
    lr: 2.5e-4
    eps: 1e-5
    max_grad_norm: 0.5
    num_steps: 128
    hidden_size: 512
    use_gae: True
    gamma: 0.99
    tau: 0.95
    use_linear_clip_decay: True
    use_linear_lr_decay: True
    reward_window_size: 50

    # Use double buffered sampling, typically helps
    # when environment time is similar or large than
    # policy inference time during rollout generation
    use_double_buffered_sampler: False
```
pointnav_rgbd_mp3d_validation_scenes.yaml:
```
ENVIRONMENT:
  MAX_EPISODE_STEPS: 500
  ITERATOR_OPTIONS:
    SHUFFLE: False
    GROUP_BY_SCENE: True
    CYCLE: False
SIMULATOR:
  AGENT_0:
    SENSORS: [ 'DEPTH_SENSOR' ]
  HABITAT_SIM_V0:
    GPU_DEVICE_ID: 0
  DEPTH_SENSOR:
    WIDTH: 256
    HEIGHT: 256
TASK:
  TYPE: Nav-v0
  SUCCESS_DISTANCE: 0.1

  SENSORS: [ 'POINTGOAL_WITH_GPS_COMPASS_SENSOR' ]
  POINTGOAL_WITH_GPS_COMPASS_SENSOR:
    GOAL_FORMAT: "POLAR"
    DIMENSIONALITY: 2
  GOAL_SENSOR_UUID: pointgoal_with_gps_compass

  MEASUREMENTS: [ 'DISTANCE_TO_GOAL', 'SUCCESS', 'SPL' ]
  SUCCESS:
    SUCCESS_DISTANCE: 0.1
DATASET:
  TYPE: PointNav-v1
  SPLIT: val
  DATA_PATH: data/datasets/pointnav/mp3d/v1/{split}/{split}.json.gz
```
and Python script to launch training:
```
import os
from habitat_baselines.common.baseline_registry import baseline_registry
from habitat_baselines.config.default import get_config as get_baselines_config

if __name__ == "__main__":
    project_dir = "/home/lci-user/Desktop/workspace/src/ros_x_habitat/"
    config = get_baselines_config(
        os.path.join(
            project_dir,
            "configs/training_configs/ppo_pointnav.yaml",
        )
    )
    trainer_init = baseline_registry.get_trainer(config.TRAINER_NAME)
    trainer = trainer_init(config)
    trainer.train()
```

The trainer seems to load assets for a few times and does not trainer at all, and it finally crashed with the following stack trace:

```
I1207 01:05:04.314258 100404 ManagedFileBasedContainer.h:210] <Scene Instance>::convertFilenameToPassedExt : Filename : data/scene_datasets/mp3d/zsNo4HB9uLZ/zsNo4HB9uLZ.glb changed to proposed scene_instance.json filename : data/scene_datasets/mp3d/zsNo4HB9uLZ/zsNo4HB9uLZ.scene_instance.json
I1207 01:05:04.314304 100404 MetadataMediator.cpp:311] ::getSceneAttributesByName : Dataset : default has no preloaded SceneAttributes or StageAttributes named : data/scene_datasets/mp3d/zsNo4HB9uLZ/zsNo4HB9uLZ.glb so loading/creating a new StageAttributes with this name, and then creating a SceneAttributes with the same name that references this stage.
I1207 01:05:04.314309 100404 ManagedFileBasedContainer.h:210] <Stage Template>::convertFilenameToPassedExt : Filename : data/scene_datasets/mp3d/zsNo4HB9uLZ/zsNo4HB9uLZ.glb changed to proposed stage_config.json filename : data/scene_datasets/mp3d/zsNo4HB9uLZ/zsNo4HB9uLZ.stage_config.json
I1207 01:05:04.314330 100404 AttributesManagerBase.h:365] <Stage Template>::createFromJsonOrDefaultInternal : Proposing JSON name : data/scene_datasets/mp3d/zsNo4HB9uLZ/zsNo4HB9uLZ.stage_config.json from original name : data/scene_datasets/mp3d/zsNo4HB9uLZ/zsNo4HB9uLZ.glb | This file  does not exist.
I1207 01:05:04.314440 100404 AbstractObjectAttributesManagerBase.h:183] File (data/scene_datasets/mp3d/zsNo4HB9uLZ/zsNo4HB9uLZ.glb) exists but is not a recognized config filename extension, so new default Stage Template attributes created and registered.
I1207 01:05:04.314466 100404 SceneDatasetAttributes.cpp:45] ::addNewSceneInstanceToDataset : Dataset : 'default' : Stage Attributes 'data/scene_datasets/mp3d/zsNo4HB9uLZ/zsNo4HB9uLZ.glb' specified in Scene Attributes exists in dataset library.
I1207 01:05:04.314471 100404 SceneDatasetAttributes.cpp:85] ::addNewSceneInstanceToDataset : Dataset : 'default' : Lighting Layout Attributes no_lights specified in Scene Attributes exists in dataset library.
I1207 01:05:04.314476 100404 Simulator.cpp:198] ::setSceneInstanceAttributes : Navmesh file location in scene instance : data/scene_datasets/mp3d/zsNo4HB9uLZ/zsNo4HB9uLZ.navmesh
I1207 01:05:04.314496 100404 Simulator.cpp:205] ::setSceneInstanceAttributes : Loading navmesh from data/scene_datasets/mp3d/zsNo4HB9uLZ/zsNo4HB9uLZ.navmesh
I1207 01:05:04.314577 100404 Simulator.cpp:208] ::setSceneInstanceAttributes : Navmesh Loaded.
I1207 01:05:04.314584 100404 SceneGraph.h:85] Created DrawableGroup: 
I1207 01:05:04.314587 100404 Simulator.cpp:243] ::setSceneInstanceAttributes : SceneInstance : data/scene_datasets/mp3d/zsNo4HB9uLZ/zsNo4HB9uLZ.glb proposed Semantic Scene Descriptor filename : data/scene_datasets/mp3d/zsNo4HB9uLZ/zsNo4HB9uLZ.house
W1207 01:05:04.344889 100404 Simulator.cpp:267] ::setSceneInstanceAttributes : All attempts to load SSD with SceneAttributes-provided name data/scene_datasets/mp3d/zsNo4HB9uLZ/zsNo4HB9uLZ.house : exist : 0 : loaded as expected type : 1
I1207 01:05:04.345036 100404 Simulator.cpp:316] ::createSceneInstance : Using scene instance-specified Light key : -no_lights-
I1207 01:05:04.345043 100404 MetadataMediator.cpp:68] ::setSimulatorConfiguration : Set new simulator config for scene/stage : data/scene_datasets/mp3d/zsNo4HB9uLZ/zsNo4HB9uLZ.glb and dataset : default which is currently active dataset.
I1207 01:05:04.345077 100404 Simulator.cpp:374] ::createSceneInstance : Start to load stage named : data/scene_datasets/mp3d/zsNo4HB9uLZ/zsNo4HB9uLZ.glb with render asset : data/scene_datasets/mp3d/zsNo4HB9uLZ/zsNo4HB9uLZ.glb and collision asset : data/scene_datasets/mp3d/zsNo4HB9uLZ/zsNo4HB9uLZ.glb
I1207 01:05:04.345089 100404 ResourceManager.cpp:249] ::loadStage : Not loading semantic mesh
I1207 01:05:04.345091 100404 ResourceManager.cpp:277] ::loadStage : start load render asset data/scene_datasets/mp3d/zsNo4HB9uLZ/zsNo4HB9uLZ.glb.
I1207 01:05:04.345093 100404 ResourceManager.cpp:691] ::loadStageInternal : Attempting to load stage data/scene_datasets/mp3d/zsNo4HB9uLZ/zsNo4HB9uLZ.glb 
I1207 01:05:04.345104 100404 ResourceManager.cpp:1265] Importing Basis files as BC7 for zsNo4HB9uLZ.glb
I1207 01:05:04.418236 100404 Simulator.cpp:392] ::createSceneInstance : Successfully loaded stage named : data/scene_datasets/mp3d/zsNo4HB9uLZ/zsNo4HB9uLZ.glb
W1207 01:05:04.418259 100404 Simulator.cpp:427] 
---
Simulator::createSceneInstance : The active scene does not contain semantic annotations. 
---
I1207 01:05:04.418287 100404 MetadataMediator.cpp:262] ::getSceneAttributesByName : Query dataset : default for SceneAttributes named : data/scene_datasets/mp3d/zsNo4HB9uLZ/zsNo4HB9uLZ.glb yields 1 candidates.  Using data/scene_datasets/mp3d/zsNo4HB9uLZ/zsNo4HB9uLZ.glb.
I1207 01:05:04.418303 100404 SceneDatasetAttributes.cpp:45] ::addNewSceneInstanceToDataset : Dataset : 'default' : Stage Attributes 'data/scene_datasets/mp3d/zsNo4HB9uLZ/zsNo4HB9uLZ.glb' specified in Scene Attributes exists in dataset library.
I1207 01:05:04.418308 100404 SceneDatasetAttributes.cpp:85] ::addNewSceneInstanceToDataset : Dataset : 'default' : Lighting Layout Attributes no_lights specified in Scene Attributes exists in dataset library.
I1207 01:05:04.418319 100404 MetadataMediator.cpp:262] ::getSceneAttributesByName : Query dataset : default for SceneAttributes named : data/scene_datasets/mp3d/zsNo4HB9uLZ/zsNo4HB9uLZ.glb yields 1 candidates.  Using data/scene_datasets/mp3d/zsNo4HB9uLZ/zsNo4HB9uLZ.glb.
I1207 01:05:04.418327 100404 SceneDatasetAttributes.cpp:45] ::addNewSceneInstanceToDataset : Dataset : 'default' : Stage Attributes 'data/scene_datasets/mp3d/zsNo4HB9uLZ/zsNo4HB9uLZ.glb' specified in Scene Attributes exists in dataset library.
I1207 01:05:04.418331 100404 SceneDatasetAttributes.cpp:85] ::addNewSceneInstanceToDataset : Dataset : 'default' : Lighting Layout Attributes no_lights specified in Scene Attributes exists in dataset library.
I1207 01:05:04.418356 100404 Simulator.cpp:171] ::reconfigure : createSceneInstance success == true for active scene name : data/scene_datasets/mp3d/zsNo4HB9uLZ/zsNo4HB9uLZ.glb with renderer.
I1207 01:05:04.418611 100404 simulator.py:221] Loaded navmesh data/scene_datasets/mp3d/zsNo4HB9uLZ/zsNo4HB9uLZ.navmesh
I1207 01:05:04.949324 100404 PhysicsManager.cpp:50] Deconstructing PhysicsManager
I1207 01:05:04.949364 100404 SemanticScene.h:43] Deconstructing SemanticScene
Traceback (most recent call last):
  File "src/training/multigoal_pointnav_trainer.py", line 42, in <module>
    trainer.train()
  File "/home/lci-user/anaconda3/envs/habitat2.0/lib/python3.6/contextlib.py", line 52, in inner
    return func(*args, **kwds)
  File "/home/lci-user/Desktop/workspace/src/habitat-lab-0.2.0/habitat_baselines/rl/ppo/ppo_trainer.py", line 784, in train
    buffer_index
  File "/home/lci-user/Desktop/workspace/src/habitat-lab-0.2.0/habitat_baselines/rl/ppo/ppo_trainer.py", line 458, in _collect_environment_result
    for index_env in range(env_slice.start, env_slice.stop)
  File "/home/lci-user/Desktop/workspace/src/habitat-lab-0.2.0/habitat_baselines/rl/ppo/ppo_trainer.py", line 458, in <listcomp>
    for index_env in range(env_slice.start, env_slice.stop)
  File "/home/lci-user/anaconda3/envs/habitat2.0/lib/python3.6/contextlib.py", line 52, in inner
    return func(*args, **kwds)
  File "/home/lci-user/Desktop/workspace/src/habitat-lab-0.2.0/habitat/core/vector_env.py", line 409, in wait_step_at
    return self._connection_read_fns[index_env]()
  File "/home/lci-user/Desktop/workspace/src/habitat-lab-0.2.0/habitat/core/vector_env.py", line 97, in __call__
    res = self.read_fn()
  File "/home/lci-user/Desktop/workspace/src/habitat-lab-0.2.0/habitat/utils/pickle5_multiprocessing.py", line 68, in recv
    buf = self.recv_bytes()
  File "/home/lci-user/anaconda3/envs/habitat2.0/lib/python3.6/multiprocessing/connection.py", line 216, in recv_bytes
    buf = self._recv_bytes(maxlength)
  File "/home/lci-user/anaconda3/envs/habitat2.0/lib/python3.6/multiprocessing/connection.py", line 407, in _recv_bytes
I1207 01:05:04.951050 100404 SceneManager.h:25] Deconstructing SceneManager
I1207 01:05:04.951056 100404 SceneGraph.h:25] Deconstructing SceneGraph
    buf = self._recv(4)
  File "/home/lci-user/anaconda3/envs/habitat2.0/lib/python3.6/multiprocessing/connection.py", line 383, in _recv
    raise EOFError
EOFError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "src/training/multigoal_pointnav_trainer.py", line 49, in <module>
    trainer.train()
  File "/home/lci-user/anaconda3/envs/habitat2.0/lib/python3.6/contextlib.py", line 52, in inner
I1207 01:05:04.951172 100404 Sensor.cpp:69] Deconstructing Sensor
    return func(*args, **kwds)
  File "/home/lci-user/Desktop/workspace/src/habitat-lab-0.2.0/habitat_baselines/rl/ppo/ppo_trainer.py", line 784, in train
    buffer_index
  File "/home/lci-user/Desktop/workspace/src/habitat-lab-0.2.0/habitat_baselines/rl/ppo/ppo_trainer.py", line 458, in _collect_environment_result
    for index_env in range(env_slice.start, env_slice.stop)
  File "/home/lci-user/Desktop/workspace/src/habitat-lab-0.2.0/habitat_baselines/rl/ppo/ppo_trainer.py", line 458, in <listcomp>
    for index_env in range(env_slice.start, env_slice.stop)
  File "/home/lci-user/anaconda3/envs/habitat2.0/lib/python3.6/contextlib.py", line 52, in inner
    return func(*args, **kwds)
  File "/home/lci-user/Desktop/workspace/src/habitat-lab-0.2.0/habitat/core/vector_env.py", line 409, in wait_step_at
    return self._connection_read_fns[index_env]()
  File "/home/lci-user/Desktop/workspace/src/habitat-lab-0.2.0/habitat/core/vector_env.py", line 97, in __call__
    res = self.read_fn()
  File "/home/lci-user/Desktop/workspace/src/habitat-lab-0.2.0/habitat/utils/pickle5_multiprocessing.py", line 68, in recv
    buf = self.recv_bytes()
  File "/home/lci-user/anaconda3/envs/habitat2.0/lib/python3.6/multiprocessing/connection.py", line 216, in recv_bytes
    buf = self._recv_bytes(maxlength)
  File "/home/lci-user/anaconda3/envs/habitat2.0/lib/python3.6/multiprocessing/connection.py", line 407, in _recv_bytes
    buf = self._recv(4)
  File "/home/lci-user/anaconda3/envs/habitat2.0/lib/python3.6/multiprocessing/connection.py", line 383, in _recv
    raise EOFError
EOFError
Exception ignored in: <bound method VectorEnv.__del__ of <habitat.core.vector_env.VectorEnv object at 0x7f3d450b8cf8>>
Traceback (most recent call last):
  File "/home/lci-user/Desktop/workspace/src/habitat-lab-0.2.0/habitat/core/vector_env.py", line 588, in __del__
    self.close()
  File "/home/lci-user/Desktop/workspace/src/habitat-lab-0.2.0/habitat/core/vector_env.py", line 456, in close
    read_fn()
  File "/home/lci-user/Desktop/workspace/src/habitat-lab-0.2.0/habitat/core/vector_env.py", line 97, in __call__
    res = self.read_fn()
  File "/home/lci-user/Desktop/workspace/src/habitat-lab-0.2.0/habitat/utils/pickle5_multiprocessing.py", line 68, in recv
    buf = self.recv_bytes()
  File "/home/lci-user/anaconda3/envs/habitat2.0/lib/python3.6/multiprocessing/connection.py", line 216, in recv_bytes
    buf = self._recv_bytes(maxlength)
  File "/home/lci-user/anaconda3/envs/habitat2.0/lib/python3.6/multiprocessing/connection.py", line 407, in _recv_bytes
    buf = self._recv(4)
  File "/home/lci-user/anaconda3/envs/habitat2.0/lib/python3.6/multiprocessing/connection.py", line 383, in _recv
    raise EOFError
EOFError: 

```

**Comment by yhymason** [comment]
Does anyone have ideas about what's going on here?

**Comment by yhymason** [comment]
Training with training set seems to work fine.

**Comment by erikwijmans** [comment]
The default number of environments is 16, which is likely uses too much GPU or system memory causes a crash. Trying set `NUM_ENVIRONMENTS` to something like 4 in the hab baselines config.
