### ISSUE TITLE
Cannot run simple Rearrange Pick environment

### ISSUE THREAD

**Issue by mpiseno** [facebookresearch/habitat-lab#805]
## Habitat-Lab and Habitat-Sim versions
Habitat-Lab: v0.2.1, hab_suite branch

Habitat-Sim: v0.2.1, main branch

## ❓ Questions and Help

**Update**
I fixed the original issue by converting all the filepaths in config.DATASET to absolute paths. Then the sim starts up, but crashes soon after with the following error:

```
(habitat) michaelpiseno@Michaels-MacBook-Pro naturalizing-rl % python run.py
2022-02-09 21:44:47,304 Initializing dataset RearrangeDataset-v0
2022-02-09 21:44:47,333 initializing sim RearrangeSim-v0
[23:56:10:303106]:[Metadata] AttributesManagerBase.h(352)::createFromJsonOrDefaultInternal : <Dataset>: Proposing JSON name : default.scene_dataset_config.json from original name : default| This file does not exist.
[23:56:10:304051]:[Metadata] AssetAttributesManager.cpp(121)::createObject : Asset attributes (capsule3DSolid:capsule3DSolid_hemiRings_4_cylRings_1_segments_12_halfLen_0.75_useTexCoords_false_useTangents_false) created and registered.
[23:56:10:304286]:[Metadata] AssetAttributesManager.cpp(121)::createObject : Asset attributes (capsule3DWireframe:capsule3DWireframe_hemiRings_8_cylRings_1_segments_16_halfLen_1) created and registered.
[23:56:10:304405]:[Metadata] AssetAttributesManager.cpp(121)::createObject : Asset attributes (coneSolid:coneSolid_segments_12_halfLen_1.25_rings_1_useTexCoords_false_useTangents_false_capEnd_true) created and registered.
[23:56:10:304424]:[Metadata] AssetAttributesManager.cpp(121)::createObject : Asset attributes (coneWireframe:coneWireframe_segments_32_halfLen_1.25) created and registered.
[23:56:10:304451]:[Metadata] AssetAttributesManager.cpp(121)::createObject : Asset attributes (cubeSolid:cubeSolid) created and registered.
[23:56:10:304471]:[Metadata] AssetAttributesManager.cpp(121)::createObject : Asset attributes (cubeWireframe:cubeWireframe) created and registered.
[23:56:10:304490]:[Metadata] AssetAttributesManager.cpp(121)::createObject : Asset attributes (cylinderSolid:cylinderSolid_rings_1_segments_12_halfLen_1_useTexCoords_false_useTangents_false_capEnds_true) created and registered.
[23:56:10:304507]:[Metadata] AssetAttributesManager.cpp(121)::createObject : Asset attributes (cylinderWireframe:cylinderWireframe_rings_1_segments_32_halfLen_1) created and registered.
[23:56:10:304520]:[Metadata] AssetAttributesManager.cpp(121)::createObject : Asset attributes (icosphereSolid:icosphereSolid_subdivs_1) created and registered.
[23:56:10:304532]:[Metadata] AssetAttributesManager.cpp(121)::createObject : Asset attributes (icosphereWireframe:icosphereWireframe_subdivs_1) created and registered.
[23:56:10:304545]:[Metadata] AssetAttributesManager.cpp(121)::createObject : Asset attributes (uvSphereSolid:uvSphereSolid_rings_8_segments_16_useTexCoords_false_useTangents_false) created and registered.
[23:56:10:304560]:[Metadata] AssetAttributesManager.cpp(121)::createObject : Asset attributes (uvSphereWireframe:uvSphereWireframe_rings_16_segments_32) created and registered.
[23:56:10:304568]:[Metadata] AssetAttributesManager.cpp(110)::AssetAttributesManager : Built default primitive asset templates : 12
[23:56:10:306483]:[Metadata] SceneDatasetAttributesManager.cpp(35)::createObject : File (default) not found, so new default dataset attributes created  and registered.
[23:56:10:306496]:[Metadata] MetadataMediator.cpp(120)::createSceneDataset : Dataset default successfully created.
[23:56:10:306508]:[Metadata] AttributesManagerBase.h(352)::createFromJsonOrDefaultInternal : <Physics Manager>: Proposing JSON name : ./data/default.physics_config.json from original name : ./data/default.physics_config.json| This file exists.
[23:56:10:307060]:[Metadata] PhysicsAttributesManager.cpp(26)::createObject : JSON Configuration File (./data/default.physics_config.json) based physics manager attributes created and registered.
[23:56:10:307073]:[Metadata] MetadataMediator.cpp(210)::setActiveSceneDatasetName : Attempting to create new dataset data/replica_cad/replicaCAD.scene_dataset_config.json
[23:56:10:307084]:[Metadata] AttributesManagerBase.h(352)::createFromJsonOrDefaultInternal : <Dataset>: Proposing JSON name : data/replica_cad/replicaCAD.scene_dataset_config.json from original name : data/replica_cad/replicaCAD.scene_dataset_config.json| This file does not exist.
[23:56:10:307109]:[Metadata] AssetAttributesManager.cpp(121)::createObject : Asset attributes (capsule3DSolid:capsule3DSolid_hemiRings_4_cylRings_1_segments_12_halfLen_0.75_useTexCoords_false_useTangents_false) created and registered.
[23:56:10:307124]:[Metadata] AssetAttributesManager.cpp(121)::createObject : Asset attributes (capsule3DWireframe:capsule3DWireframe_hemiRings_8_cylRings_1_segments_16_halfLen_1) created and registered.
[23:56:10:307143]:[Metadata] AssetAttributesManager.cpp(121)::createObject : Asset attributes (coneSolid:coneSolid_segments_12_halfLen_1.25_rings_1_useTexCoords_false_useTangents_false_capEnd_true) created and registered.
[23:56:10:307156]:[Metadata] AssetAttributesManager.cpp(121)::createObject : Asset attributes (coneWireframe:coneWireframe_segments_32_halfLen_1.25) created and registered.
[23:56:10:307166]:[Metadata] AssetAttributesManager.cpp(121)::createObject : Asset attributes (cubeSolid:cubeSolid) created and registered.
[23:56:10:307175]:[Metadata] AssetAttributesManager.cpp(121)::createObject : Asset attributes (cubeWireframe:cubeWireframe) created and registered.
[23:56:10:307189]:[Metadata] AssetAttributesManager.cpp(121)::createObject : Asset attributes (cylinderSolid:cylinderSolid_rings_1_segments_12_halfLen_1_useTexCoords_false_useTangents_false_capEnds_true) created and registered.
[23:56:10:307203]:[Metadata] AssetAttributesManager.cpp(121)::createObject : Asset attributes (cylinderWireframe:cylinderWireframe_rings_1_segments_32_halfLen_1) created and registered.
[23:56:10:307214]:[Metadata] AssetAttributesManager.cpp(121)::createObject : Asset attributes (icosphereSolid:icosphereSolid_subdivs_1) created and registered.
[23:56:10:307224]:[Metadata] AssetAttributesManager.cpp(121)::createObject : Asset attributes (icosphereWireframe:icosphereWireframe_subdivs_1) created and registered.
[23:56:10:307236]:[Metadata] AssetAttributesManager.cpp(121)::createObject : Asset attributes (uvSphereSolid:uvSphereSolid_rings_8_segments_16_useTexCoords_false_useTangents_false) created and registered.
[23:56:10:307248]:[Metadata] AssetAttributesManager.cpp(121)::createObject : Asset attributes (uvSphereWireframe:uvSphereWireframe_rings_16_segments_32) created and registered.
[23:56:10:307259]:[Metadata] AssetAttributesManager.cpp(110)::AssetAttributesManager : Built default primitive asset templates : 12
[23:56:10:307414]:[Metadata] SceneDatasetAttributesManager.cpp(35)::createObject : File (data/replica_cad/replicaCAD.scene_dataset_config.json) not found, so new default dataset attributes created  and registered.
[23:56:10:307419]:[Metadata] MetadataMediator.cpp(120)::createSceneDataset : Dataset data/replica_cad/replicaCAD.scene_dataset_config.json successfully created.
[23:56:10:307424]:[Metadata] MetadataMediator.cpp(217)::setActiveSceneDatasetName : Attempt to create new dataset data/replica_cad/replicaCAD.scene_dataset_config.json   succeeded. Currently active dataset : data/replica_cad/replicaCAD.scene_dataset_config.json
[23:56:10:307429]:[Metadata] MetadataMediator.cpp(175)::setCurrPhysicsAttributesHandle : Old physics manager attributes  changed to ./data/default.physics_config.json successfully.
[23:56:10:307436]:[Metadata] MetadataMediator.cpp(66)::setSimulatorConfiguration : Set new simulator config for scene/stage : data/replica_cad/configs/scenes/v3_sc2_staging_20.scene_instance.json and dataset : data/replica_cad/replicaCAD.scene_dataset_config.json which is currently active dataset.
Renderer: Apple M1 Pro by Apple
OpenGL version: 4.1 Metal - 76.3
Using optional features:
    GL_ARB_vertex_array_object
    GL_ARB_ES2_compatibility
    GL_ARB_separate_shader_objects
    GL_ARB_texture_storage
    GL_EXT_texture_filter_anisotropic
    GL_EXT_debug_label
    GL_EXT_debug_marker
Using driver workarounds:
    no-layout-qualifiers-on-old-glsl
    apple-buffer-texture-unbind-on-buffer-modify
[23:56:10:558593]:[Metadata] MetadataMediator.cpp(297)::getSceneInstanceAttributesByName : Dataset : data/replica_cad/replicaCAD.scene_dataset_config.json has no preloaded SceneInstanceAttributes or StageAttributes named : data/replica_cad/configs/scenes/v3_sc2_staging_20.scene_instance.json so loading/creating a new StageAttributes with this name, and then creating a SceneInstanceAttributes with the same name that references this stage.
[23:56:10:558645]:[Metadata] AttributesManagerBase.h(352)::createFromJsonOrDefaultInternal : <Stage Template>: Proposing JSON name : data/replica_cad/configs/scenes/v3_sc2_staging_20.scene_instance.stage_config.json from original name : data/replica_cad/configs/scenes/v3_sc2_staging_20.scene_instance.json| This file does not exist.
[23:56:10:558695]:[Metadata] StageAttributesManager.cpp(86)::registerObjectFinalize : Render asset template handle : data/replica_cad/configs/scenes/v3_sc2_staging_20.scene_instance.json specified in stage template with handle : data/replica_cad/configs/scenes/v3_sc2_staging_20.scene_instance.json does not correspond to any existing file or primitive render asset.  Aborting.
[23:56:10:559791]:[Scene] SceneManager.h(25)::~SceneManager : Deconstructing SceneManager
[23:56:10:560397]:[Gfx] Renderer.cpp(72)::~Impl : Deconstructing Renderer
[23:56:10:560554]:[Gfx] WindowlessContext.h(17)::~WindowlessContext : Deconstructing WindowlessContext
Traceback (most recent call last):
  File "run.py", line 31, in <module>
    env = habitat.Env(config=get_config())
  File "/Users/michaelpiseno/src/habitat-lab/habitat/core/env.py", line 108, in __init__
    id_sim=self._config.SIMULATOR.TYPE, config=self._config.SIMULATOR
  File "/Users/michaelpiseno/src/habitat-lab/habitat/sims/registration.py", line 19, in make_sim
    return _sim(**kwargs)
  File "/Users/michaelpiseno/src/habitat-lab/habitat/tasks/rearrange/rearrange_sim.py", line 37, in __init__
    super().__init__(config)
  File "/Users/michaelpiseno/src/habitat-lab/habitat/sims/habitat_simulator/habitat_simulator.py", line 272, in __init__
    super().__init__(self.sim_config)
  File "<attrs generated init habitat_sim.simulator.Simulator>", line 11, in __init__
  File "/Users/michaelpiseno/opt/anaconda3/envs/habitat/lib/python3.7/site-packages/habitat_sim-0.2.1-py3.7-macosx-10.9-x86_64.egg/habitat_sim/simulator.py", line 122, in __attrs_post_init__
    self.__set_from_config(self.config)
  File "/Users/michaelpiseno/opt/anaconda3/envs/habitat/lib/python3.7/site-packages/habitat_sim-0.2.1-py3.7-macosx-10.9-x86_64.egg/habitat_sim/simulator.py", line 260, in __set_from_config
    self._config_backend(config)
  File "/Users/michaelpiseno/opt/anaconda3/envs/habitat/lib/python3.7/site-packages/habitat_sim-0.2.1-py3.7-macosx-10.9-x86_64.egg/habitat_sim/simulator.py", line 204, in _config_backend
    super().__init__(config.sim_cfg, config.metadata_mediator)
AssertionError: ESP_CHECK failed: Missing (at least) one of scene dataset attributes, stage attributes, or dataset scene attributes for scene 'data/replica_cad/configs/scenes/v3_sc2_staging_20.scene_instance.json'.  Likely an invalid scene name.
```

The scene 'data/replica_cad/configs/scenes/v3_sc2_staging_20.scene_instance.json' is not in the replica_cad dataset, so I'm not sure what the issue is here.

---
**Original Issue**

I cannot get Habitat working for a rearrange pick task toy example. I am following the [Habitat 2.0 Quick Start Tutorial](https://colab.research.google.com/github/facebookresearch/habitat-lab/blob/hab_suite/examples/tutorials/colabs/Habitat2_Quickstart.ipynb) linked in other issues, but I get an error saying the Rearrange task assets are not downloaded (they are). Also, I am running my code from a separate directory (not habitat-lab/) Here is my code:

```python
import os

import gym
import habitat
import habitat_baselines.utils.gym_definitions as habitat_gym
from habitat.utils.visualizations.utils import observations_to_image
from habitat_baselines.utils.render_wrapper import overlay_frame
from habitat_sim.utils import viz_utils as vut


def get_config():
    config = habitat.get_config(
        os.path.join(
            habitat_gym.config_base_dir,
            "configs/tasks/rearrange/pick.yaml",
        )
    )

    return config

# Load embodied AI task (RearrangePick) and a pre-specified virtual robot
env = habitat.Env(config=get_config())

observations = env.reset()
```

And here is the error:

```
(habitat) michaelpiseno@Michaels-MacBook-Pro naturalizing-rl % python run.py 
2022-02-09 21:12:27,412 Initializing dataset RearrangeDataset-v0
2022-02-09 21:12:27,412 Rearrange task assets are not downloaded locally, downloading and extracting now...
No data-path provided, default to: /Users/michaelpiseno/src/naturalizing-rl/data. Use '--data-path' to specify another location.
Traceback (most recent call last):
  File "run.py", line 22, in <module>
    env = habitat.Env(config=get_config())
  File "/Users/michaelpiseno/src/habitat-lab/habitat/core/env.py", line 78, in __init__
    id_dataset=config.DATASET.TYPE, config=config.DATASET
  File "/Users/michaelpiseno/src/habitat-lab/habitat/datasets/registration.py", line 21, in make_dataset
    return _dataset(**kwargs)  # type: ignore
  File "/Users/michaelpiseno/src/habitat-lab/habitat/datasets/rearrange/rearrange_dataset.py", line 56, in __init__
    ["--uids", "rearrange_task_assets", "--no-replace"]
  File "/Users/michaelpiseno/opt/anaconda3/envs/habitat/lib/python3.7/site-packages/habitat_sim-0.2.1-py3.7-macosx-10.9-x86_64.egg/habitat_sim/utils/datasets_download.py", line 579, in main
    uid, data_path, args.username, args.password, replace
  File "/Users/michaelpiseno/opt/anaconda3/envs/habitat/lib/python3.7/site-packages/habitat_sim-0.2.1-py3.7-macosx-10.9-x86_64.egg/habitat_sim/utils/datasets_download.py", line 402, in download_and_place
    subprocess.check_call(shlex.split(download_command))
  File "/Users/michaelpiseno/opt/anaconda3/envs/habitat/lib/python3.7/subprocess.py", line 358, in check_call
    retcode = call(*popenargs, **kwargs)
  File "/Users/michaelpiseno/opt/anaconda3/envs/habitat/lib/python3.7/subprocess.py", line 339, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/Users/michaelpiseno/opt/anaconda3/envs/habitat/lib/python3.7/subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "/Users/michaelpiseno/opt/anaconda3/envs/habitat/lib/python3.7/subprocess.py", line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'wget': 'wget'
```

Looks like there may be two issues here actually. First, it is not recognizing that the files are already downloaded. Second, the dataset_download script is failing. My data files are arranged exactly as specified in the "configs/tasks/rearrange/pick.yaml" file. Thanks in advance!

**Comment by vincentpierre** [comment]
It looks like you are missing a specific file in the replica_cad dataset. I would advise re-downloading it : 
`python -m habitat_sim.utils.datasets_download --uids replica_cad_dataset` 
I was able to reproduce your error by deleting
`rm data/replica_cad/configs/scenes/v3_sc2_staging_20.scene_instance.json`
and fixed it with the command above.
Make sure to be on the latest versions since you could be using an old data set from habitat-sim.
I hope this helps!
