### ISSUE TITLE
FileNotFoundError during SAVI training

### ISSUE THREAD

**Issue by sivannavis** [facebookresearch/habitat-lab#931]
Hi! I encountered this issue in soundspaces repo, but think it has something to do with habitat-lab as well, so posting here for some help: 
When I run `ss_baselines.savi.run` with savi_pretraining.yaml, I run into these errors: `FileNotFoundError: data/metadata/default/ZMojNkEp431/points.txt not found.` Why would the metadata_dir function in simulator.py look for `config.SCENE_DATASET = default` while in confige the value is "mp3d"?
I'm running savi/run.py on 1 node with 2 GPUs. I attached the error logs below.
Thank you so much!

> INFO:torch.distributed.distributed_c10d:Added key: store_based_barrier_key:1 to store for rank: 0
INFO:torch.distributed.distributed_c10d:Added key: store_based_barrier_key:1 to store for rank: 1
INFO:torch.distributed.distributed_c10d:Rank 1: Completed store-based barrier for key:store_based_barrier_key:1 with 2 nodes.
INFO:torch.distributed.distributed_c10d:Rank 0: Completed store-based barrier for key:store_based_barrier_key:1 with 2 nodes.
2022-08-22 17:19:35,903 Initializing dataset SemanticAudioNav
2022-08-22 17:19:35,903 Initializing dataset SemanticAudioNav
INFO:root:Sampled 0 episodes from 0 scenes.
INFO:root:Sampled 0 episodes from 0 scenes.
INFO:root:Using VectorEnv
INFO:root:Using VectorEnv
2022-08-22 17:19:47,443 Initializing dataset SemanticAudioNav
2022-08-22 17:19:47,443 Initializing dataset SemanticAudioNav
2022-08-22 17:19:47,472 Initializing dataset SemanticAudioNav
2022-08-22 17:19:47,473 Initializing dataset SemanticAudioNav
2022-08-22 17:19:47,474 Initializing dataset SemanticAudioNav
2022-08-22 17:19:47,475 Initializing dataset SemanticAudioNav
2022-08-22 17:19:47,530 Initializing dataset SemanticAudioNav
2022-08-22 17:19:47,752 Initializing dataset SemanticAudioNav
2022-08-22 17:19:47,828 Initializing dataset SemanticAudioNav
2022-08-22 17:19:48,055 Initializing dataset SemanticAudioNav
2022-08-22 17:19:48,224 Initializing dataset SemanticAudioNav
2022-08-22 17:19:48,283 Initializing dataset SemanticAudioNav
2022-08-22 17:19:48,283 Initializing dataset SemanticAudioNav
2022-08-22 17:19:48,283 Initializing dataset SemanticAudioNav
2022-08-22 17:19:48,283 Initializing dataset SemanticAudioNav
2022-08-22 17:19:48,291 Initializing dataset SemanticAudioNav
2022-08-22 17:19:48, INFO: Sampled 12908 episodes from 7 scenes.
2022-08-22 17:19:48,363 initializing sim SoundSpacesSim
Process ForkServerProcess-5:
Traceback (most recent call last):
  File "/ext3/miniconda3/envs/soundspaces/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/ext3/miniconda3/envs/soundspaces/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/ext3/miniconda3/envs/soundspaces/lib/python3.8/contextlib.py", line 75, in inner
    return func(*args, **kwds)
  File "/ext3/code/habitat-lab/habitat/core/vector_env.py", line 233, in _worker_env
    env = env_fn(*env_fn_args)
  File "/ext3/code/sound-spaces/ss_baselines/common/env_utils.py", line 134, in make_env_fn
    env = env_class(config=config, dataset=dataset)
  File "/ext3/code/sound-spaces/ss_baselines/common/environments.py", line 48, in __init__
    super().__init__(self._core_env_config, dataset)
  File "/ext3/code/habitat-lab/habitat/core/env.py", line 374, in __init__
    self._env = Env(config, dataset)
  File "/ext3/code/habitat-lab/habitat/core/env.py", line 104, in __init__
    self._sim = make_sim(
  File "/ext3/code/habitat-lab/habitat/sims/registration.py", line 19, in make_sim
    return _sim(**kwargs)
  File "/ext3/code/sound-spaces/soundspaces/simulator.py", line 135, in __init__
    self.points, self.graph = load_metadata(self.metadata_dir)
  File "/ext3/code/sound-spaces/soundspaces/utils.py", line 27, in load_metadata
    points_data = np.loadtxt(points_file, delimiter="\t")
  File "/ext3/miniconda3/envs/soundspaces/lib/python3.8/site-packages/numpy/lib/npyio.py", line 1042, in loadtxt
    fh = np.lib._datasource.open(fname, 'rt', encoding=encoding)
  File "/ext3/miniconda3/envs/soundspaces/lib/python3.8/site-packages/numpy/lib/_datasource.py", line 193, in open
    return ds.open(path, mode, encoding=encoding, newline=newline)
  File "/ext3/miniconda3/envs/soundspaces/lib/python3.8/site-packages/numpy/lib/_datasource.py", line 532, in open
    raise FileNotFoundError(f"{path} not found.")
FileNotFoundError: data/metadata/default/jh4fc5c5qoQ/points.txt not found.
2022-08-22 17:19:49, INFO: Sampled 12908 episodes from 7 scenes.
2022-08-22 17:19:49,209 initializing sim SoundSpacesSim
Process ForkServerProcess-5:
Traceback (most recent call last):
  File "/ext3/miniconda3/envs/soundspaces/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/ext3/miniconda3/envs/soundspaces/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/ext3/miniconda3/envs/soundspaces/lib/python3.8/contextlib.py", line 75, in inner
    return func(*args, **kwds)
  File "/ext3/code/habitat-lab/habitat/core/vector_env.py", line 233, in _worker_env
    env = env_fn(*env_fn_args)
  File "/ext3/code/sound-spaces/ss_baselines/common/env_utils.py", line 134, in make_env_fn
    env = env_class(config=config, dataset=dataset)
  File "/ext3/code/sound-spaces/ss_baselines/common/environments.py", line 48, in __init__
    super().__init__(self._core_env_config, dataset)
  File "/ext3/code/habitat-lab/habitat/core/env.py", line 374, in __init__
    self._env = Env(config, dataset)
  File "/ext3/code/habitat-lab/habitat/core/env.py", line 104, in __init__
    self._sim = make_sim(
  File "/ext3/code/habitat-lab/habitat/sims/registration.py", line 19, in make_sim
    return _sim(**kwargs)
  File "/ext3/code/sound-spaces/soundspaces/simulator.py", line 135, in __init__
    self.points, self.graph = load_metadata(self.metadata_dir)
  File "/ext3/code/sound-spaces/soundspaces/utils.py", line 27, in load_metadata
    points_data = np.loadtxt(points_file, delimiter="\t")
  File "/ext3/miniconda3/envs/soundspaces/lib/python3.8/site-packages/numpy/lib/npyio.py", line 1042, in loadtxt
    fh = np.lib._datasource.open(fname, 'rt', encoding=encoding)
  File "/ext3/miniconda3/envs/soundspaces/lib/python3.8/site-packages/numpy/lib/_datasource.py", line 193, in open
    return ds.open(path, mode, encoding=encoding, newline=newline)
  File "/ext3/miniconda3/envs/soundspaces/lib/python3.8/site-packages/numpy/lib/_datasource.py", line 532, in open
    raise FileNotFoundError(f"{path} not found.")
FileNotFoundError: data/metadata/default/ZMojNkEp431/points.txt not found.

This is still the case when I evaluate the pretrained model using `py ss_baselines/savi/run.py --run-type eval --exp-config ss_baselines/savi/config/semantic_audionav/savi.yaml EVAL_CKPT_PATH_DIR data/pretrained_weights/semantic_audionav/savi/best_val.pth EVAL.SPLIT test USE_SYNC_VECENV True RL.DDPPO.pretrained False`

After some debugging I noticed `config.TASK_CONFIG` is good before the `make_env_fn` function. And it seems it's this part in initializing the `Env` Class that changes the `SCENE_DATASET` to "default", which I'm a bit confused about: 
https://github.com/facebookresearch/habitat-lab/blob/380ac0a7d8c4ead1532f109b15d329473212eae9/habitat/core/env.py#L94-L96

https://github.com/facebookresearch/habitat-lab/blob/380ac0a7d8c4ead1532f109b15d329473212eae9/habitat/core/dataset.py#L59-L61

Could you help me take a look and point me on the right way?

_Originally posted by @sivannavis in https://github.com/facebookresearch/sound-spaces/issues/89#issuecomment-1223389426_

**Comment by sreeharshaparuchur1** [comment]
Hey @sivannavis !

I'm facing a similar error while trying to run the av_wan baseline from the soundspaces repo. I too have traced this absurd behaviour of the path changing to 'default' instead of 'mp3d' (replica, in my case) down to this part in the code. May I know if you have figuired a work around for the same that does not have an effect on the way habitat-sim goes about its task.

I am using habitat2.2, are you using the same version?

**Comment by sivannavis** [comment]
@sreeharshaparuchur1 Hi! Yes, I'm using the same version 2.2, and my workaround is just simply commenting this part that changes the scene_dataset string, in this thread https://github.com/facebookresearch/sound-spaces/issues/89#issuecomment-1233326255 .

**Comment by sreeharshaparuchur1** [comment]
@sivannavis Ah, yeah I did that too. It seems to work alright, even with other baselines. It does beg the question as to why it was added in the first place. Also, are you running code with soundspaces 2.0 or soundspaces 1.0?

**Comment by sivannavis** [comment]
I think I'm running soundspaces 1.0. I do have the same question though...

**Comment by sivannavis** [comment]
After some checking, it turns out to be a version mismatch between Habitat-lab and SAVI code. I rolled back to version 0.2.1 and problem solved.
